const wordClues = [
  { word: "hello", clue: "A common greeting to start a conversation" },
  { word: "world", clue: "Planet we call home; '___ War II'" },
  { word: "nest", clue: "A cozy home built by birds" },
  { word: "humdrum", clue: "Lacking excitement or variety" },
  { word: "bird", clue: "Feathered friend known for its song" },
  { word: "addicted", clue: "Unable to quit, like many to caffeine" },
  { word: "carve", clue: "To sculpt from wood or pumpkin, perhaps" },
  { word: "wriggle", clue: "Twist and turn like a worm" },
  { word: "wound", clue: "An injury or what you do to a clock" },
  { word: "lamentable", clue: "Deserving of grief or regret" },
  { word: "paste", clue: "Sticky substance or an option in an edit menu" },
  { word: "known", clue: "Familiar or recognized" },
  { word: "girl", clue: "A young female person" },
  { word: "dime", clue: "Ten cents or a thin piece of change" },
  { word: "ultra", clue: "Beyond in prefixes" },
  { word: "cemetery", clue: "A resting place for the deceased" },
  { word: "unused", clue: "Like new or never before employed" },
  { word: "delay", clue: "A pause or hiatus, often frustrating" },
  { word: "sparkle", clue: "Glisten or twinkle, as diamonds might" },
  { word: "lopsided", clue: "Unbalanced or unevenly distributed" },
  { word: "windy", clue: "Characteristic of Chicago's weather or speech" },
  { word: "pushy", clue: "Overly assertive or aggressive" },
  { word: "scrawny", clue: "Thin and bony, needing a sandwich perhaps" },
  { word: "science", clue: "Subject dealing with facts and experiments" },
  { word: "rambunctious", clue: "Uncontrollably exuberant or boisterous" },
  { word: "faulty", clue: "Malfunctioning or defective" },
  { word: "society", clue: "Community of people or high social standing" },
  { word: "squeeze", clue: "To compress or a tight hug" },
  { word: "view", clue: "Scene or perspective to behold" },
  { word: "street", clue: "Urban road or Sesame location" },
  { word: "ladybug", clue: "Spotted beetle or a gardener's friend" },
  { word: "divergent", clue: "Going in different directions; a novel series" },
  { word: "jewel", clue: "Precious stone or a gem" },
  { word: "desert", clue: "Dry and barren land or to abandon" },
  { word: "copper", clue: "Element found in pennies or wiring" },
  { word: "electric", clue: "Type of energy or atmosphere at a live concert" },
  { word: "ablaze", clue: "Burning fiercely or alight" },
  { word: "outrageous", clue: "Shocking or scandalous behavior" },
  { word: "coherent", clue: "Logically connected or clear speaking" },
  { word: "railway", clue: "Path for trains or method of transportation" },
  { word: "scary", clue: "Spine-tingling or something frightful" },
  { word: "encouraging", clue: "Giving hope or support" },
  { word: "typical", clue: "Characteristic or expected" },
  { word: "elated", clue: "Filled with joy or in high spirits" },
  { word: "motion", clue: "Movement or a formal proposal" },
  { word: "crowded", clue: "Packed tightly or lacking space" },
  { word: "babies", clue: "Infants or youngest members" },
  { word: "air", clue: "What we breathe or broadcast" },
  { word: "special", clue: "Distinct or unique; not ordinary" },
  { word: "secret", clue: "Something hidden or not meant to be known" },
  { word: "rose", clue: "A fragrant flower or to get up from a seat" },
  { word: "permissible", clue: "Allowed or acceptable under the law" },
  { word: "general", clue: "Widespread or a high-ranking military officer" },
  { word: "team", clue: "A group working together or sports unit" },
  { word: "hapless", clue: "Unlucky or unfortunate" },
  { word: "substantial", clue: "Of considerable importance or size" },
  { word: "spectacular", clue: "Impressive or dramatic show" },
  { word: "drunk", clue: "Intoxicated or inebriated state" },
  { word: "join", clue: "To connect or become a member" },
  { word: "dolls", clue: "Children's playthings resembling humans" },
  { word: "wander", clue: "To roam without a destination" },
  { word: "wild", clue: "Untamed or natural; not domesticated" },
  { word: "sour", clue: "Taste of citrus or mood of displeasure" },
  { word: "promise", clue: "A declaration or assurance of action" },
  { word: "filthy", clue: "Extremely dirty" },
  { word: "tearful", clue: "Weeping or filled with emotion" },
  { word: "sock", clue: "Footwear item or a punch" },
  { word: "perpetual", clue: "Never ending or eternal" },
  { word: "efficient", clue: "Performing in the best possible manner" },
  { word: "skip", clue: "To leap lightly or miss out" },
  { word: "fax", clue: "A document sent over a phone line" },
  { word: "effect", clue: "A result or impact of an action" },
  { word: "reaction", clue: "Response to an action or event" },
  { word: "womanly", clue: "Having qualities traditionally ascribed to women" },
  { word: "van", clue: "A type of vehicle used for transport" },
  { word: "necessary", clue: "Essential or needed" },
  { word: "bored", clue: "Uninterested or tired of the world" },
  { word: "ordinary", clue: "Normal or common, nothing special" },
  { word: "big", clue: "Of large size or major concern" },
  { word: "suspend", clue: "To hang something or pause" },
  { word: "day", clue: "A 24-hour period or when the sun is up" },
  { word: "library", clue: "A place filled with books for public use" },
  { word: "zany", clue: "Comical in an odd or whimsical manner" },
  { word: "tail", clue: "A part of an animal's body or to follow secretly" },
  { word: "crooked", clue: "Bent or dishonest" },
  { word: "bounce", clue: "To spring back or lively movement" },
  { word: "arrive", clue: "To reach a destination" },
  { word: "admit", clue: "To confess or allow entry" },
  { word: "texture", clue: "Feel or appearance of a surface or fabric" },
  { word: "credit", clue: "Recognition or borrowing power" },
  { word: "broad", clue: "Wide or including a wide variety" },
  { word: "swing", clue: "To move back and forth or a type of dance" },
  { word: "offer", clue: "To present for acceptance" },
  { word: "sturdy", clue: "Strongly built or robust" },
  { word: "obtainable", clue: "Possible to be gotten or acquired" },
  { word: "point", clue: "A sharp tip or to direct attention" },
  { word: "hose", clue: "A flexible tube for conveying fluids" },
  { word: "polish", clue: "To make shine or refine" },
  { word: "available", clue: "Ready for use or not busy" },
  { word: "account", clue: "A report or financial record" },
  { word: "umbrella", clue: "Rain shield or a Rihanna hit" },
  { word: "dead", clue: "No longer living or a complete stop" },
  { word: "nine", clue: "Number of lives cats are said to have" },
  { word: "car", clue: "Automobile or transportation choice" },
  { word: "escape", clue: "Get away or a key on a keyboard" },
  { word: "faithful", clue: "Loyal and steadfast" },
  { word: "dramatic", clue: "Theatrical or emotionally intense" },
  { word: "distance", clue: "Space between two points" },
  { word: "mask", clue: "Cover for the face or conceal one's identity" },
  { word: "annoy", clue: "Bother persistently or irritate" },
  { word: "pick", clue: "To choose or a tool for a guitarist" },
  { word: "glove", clue: "Hand covering or baseball catcher's gear" },
  { word: "grate", clue: "Shred, as cheese, or a fireplace barrier" },
  { word: "room", clue: "A space within a building" },
  { word: "price", clue: "Cost or value on a tag" },
  { word: "crime", clue: "An unlawful act or a detective's case" },
  { word: "screw", clue: "Fastener turned with a Phillips head" },
  { word: "ratty", clue: "Shabby or frayed" },
  { word: "include", clue: "Contain as part of a whole" },
  { word: "cup", clue: "Tea holder or sports trophy" },
  { word: "building", clue: "A structure with a roof and walls" },
  { word: "add", clue: "To combine or perform simple math" },
  { word: "pump", clue: "A device to move fluid or a type of shoe" },
  { word: "knowledgeable", clue: "Well-informed or educated" },
  { word: "push", clue: "Exert force or strongly encourage" },
  { word: "numerous", clue: "Many or several" },
  { word: "command", clue: "To direct with authority" },
  { word: "versed", clue: "Experienced or skilled" },
  { word: "spy", clue: "Secret agent or snoop" },
  { word: "eyes", clue: "Sight organs or things you can't take off someone" },
  { word: "clip", clue: "Fasten or a segment from a show" },
  { word: "tasty", clue: "Flavorful or delicious" },
  { word: "silent", clue: "Mute or without sound" },
  { word: "hospitable", clue: "Welcoming or warm to guests" },
  { word: "punch", clue: "To strike with a fist or a party drink" },
  { word: "scale", clue: "Device for measuring weight or to climb" },
  { word: "enormous", clue: "Very large or immense" },
  { word: "tin", clue: "Metal container or tin can telephone component" },
  { word: "squalid", clue: "Filthy and neglected" },
  { word: "delightful", clue: "Pleasing or charming" },
  { word: "aggressive", clue: "Forceful or assertive" },
  { word: "minister", clue: "Religious leader or government official" },
  { word: "glib", clue: "Smooth-talking or slick" },
  { word: "harmony", clue: "Accord in music or relationships" },
  { word: "irate", clue: "Furious or raging" },
  { word: "depressed", clue: "Downhearted or in a low economic state" },
  { word: "kiss", clue: "To smooch or a small confectionary" },
  { word: "irritating", clue: "Annoying or causing discomfort" },
  { word: "fretful", clue: "Worried or distressed" },
  { word: "vengeful", clue: "Desiring revenge or retribution" },
    { word: "request", clue: "To ask for something politely or formally" },
  { word: "foot", clue: "A unit of measurement or part of the leg" },
  { word: "plant", clue: "Organism that photosynthesizes or to place firmly" },
  { word: "drink", clue: "A beverage or to consume liquids" },
  { word: "bad", clue: "Not good or misbehaving" },
  { word: "flame", clue: "Fire's visible part or a passionate romance" },
  { word: "mailbox", clue: "A receptacle for postal deliveries" },
  { word: "ahead", clue: "In the future or in front" },
  { word: "juice", clue: "Fruit extract or electrical power, informally" },
  { word: "acoustic", clue: "Relating to sound or an unplugged performance" },
  { word: "whole", clue: "Entire or unbroken" },
  { word: "tank", clue: "Large container or military vehicle" },
  { word: "wholesale", clue: "In bulk or a type of trade" },
  { word: "draconian", clue: "Harsh or severe, as laws" },
  { word: "observation", clue: "The act of watching or a remark" },
  { word: "comb", clue: "To untangle hair or a fine-toothed instrument" },
  { word: "delirious", clue: "In an ecstatic or hallucinatory state" },
  { word: "believe", clue: "To accept as true or have faith" },
  { word: "shrug", clue: "Gesture of indifference or uncertainty" },
  { word: "joyous", clue: "Full of happiness or great delight" },
  { word: "meat", clue: "Animal flesh consumed as food" },
  { word: "zesty", clue: "Pleasantly piquant or spicy" },
  { word: "scrub", clue: "To clean vigorously or cancel, slangily" },
  { word: "lackadaisical", clue: "Lacking enthusiasm or carelessly lazy" },
  { word: "laugh", clue: "To express mirth or amusement" },
  { word: "flowers", clue: "Blooms or blossoms in a garden" },
  { word: "bore", clue: "To drill a hole or cause ennui" },
  { word: "suck", clue: "To draw into the mouth or be very bad, informally" },
  { word: "spotless", clue: "Immaculately clean or unblemished" },
  { word: "expansion", clue: "The act of increasing in size or scope" },
  { word: "stomach", clue: "Digestive organ or to endure" },
  { word: "approval", clue: "Formal consent or positive regard" },
  { word: "wide-eyed", clue: "Naive or with an innocent surprise" },
  { word: "like", clue: "Similar to or fond of" },
  { word: "distinct", clue: "Clearly different or notable" },
  { word: "rude", clue: "Lacking manners or refinement" },
  { word: "knife", clue: "Utensil for cutting or a weapon" },
  { word: "boil", clue: "To heat a liquid to bubbling or a skin abscess" },
  { word: "admire", clue: "Regard with respect or warm approval" },
  { word: "tick", clue: "A tiny blood-sucking arachnid or a mattress noise" },
  { word: "whispering", clue: "Speaking softly or murmuring sound" },
  { word: "cuddly", clue: "Inviting a hug or endearingly soft" },
  { word: "fearful", clue: "Feeling afraid or causing dread" },
  { word: "act", clue: "To do something or a segment in a play" },
  { word: "quiver", clue: "To shake or tremble or an arrow holder" },
  { word: "envious", clue: "Feeling or showing jealousy" },
  { word: "friends", clue: "Companions or a popular TV sitcom" },
  { word: "concern", clue: "Worry or to involve, matter" },
  { word: "horrible", clue: "Causing horror or very bad" },
  { word: "volcano", clue: "A mountain with a fiery temper" },
  { word: "eggs", clue: "Breakfast staple or subjects of an Easter hunt" },
  { word: "ossified", clue: "Turned to bone or very drunk, informally" },
  { word: "canvas", clue: "Painter's surface or sturdy fabric" },
  { word: "use", clue: "To employ for a purpose" },
  { word: "fool", clue: "To deceive or a court jester" },
  { word: "want", clue: "To desire or lack" },
  { word: "important", clue: "Of great significance or high priority" },
  { word: "parched", clue: "Extremely thirsty or dry" },
  { word: "listen", clue: "To give one's attention to sound" },
  { word: "march", clue: "To walk steadily or a month named for Mars" },
  { word: "humor", clue: "Quality of being amusing or comical" },
  { word: "hover", clue: "To remain floating or linger close by" },
  { word: "joke", clue: "Amusing story" },
  { word: "greedy", clue: "Excessively desirous" },
  { word: "story", clue: "Narrative" },
  { word: "back", clue: "Rear part" },
  { word: "nonchalant", clue: "Casually indifferent" },
  { word: "toothpaste", clue: "Dental hygiene product" },
  { word: "hollow", clue: "Empty inside" },
  { word: "unit", clue: "Individual component" },
  { word: "didactic", clue: "Intended to teach" },
  { word: "fuel", clue: "Substance for burning" },
  { word: "wind", clue: "Movement of air" },
  { word: "describe", clue: "Explain in detail" },
  { word: "overrated", clue: "Not as good as claimed" },
  { word: "church", clue: "House of worship" },
  { word: "concentrate", clue: "Focus attention" },
  { word: "cub", clue: "Baby bear" },
  { word: "lumber", clue: "Wood material" },
  { word: "double", clue: "Two times as much" },
  { word: "passenger", clue: "Traveler" },
  { word: "dry", clue: "Free from moisture" },
  { word: "butter", clue: "Dairy product" },
  { word: "squeak", clue: "High-pitched sound" },
  { word: "friction", clue: "Resistance between surfaces" },
  { word: "cook", clue: "Prepare food" },
  { word: "victorious", clue: "Winning" },
  { word: "bead", clue: "Small decorative object" },
  { word: "huge", clue: "Very large" },
  { word: "melted", clue: "Changed from solid to liquid" },
  { word: "smiling", clue: "Expressing happiness" },
  { word: "cover", clue: "Protective layer" },
  { word: "rain", clue: "Water falling from the sky" },
  { word: "late", clue: "After the expected time" },
  { word: "volatile", clue: "Easily evaporating" },
  { word: "wakeful", clue: "Unable to sleep" },
  { word: "legs", clue: "Lower limbs" },
  { word: "breathe", clue: "Inhale and exhale" },
  { word: "glamorous", clue: "Attractive and stylish" },
  { word: "thrill", clue: "Excitement" },
  { word: "adaptable", clue: "Able to adjust" },
  { word: "worry", clue: "Feel anxious" },
  { word: "optimal", clue: "Most favorable" },
  { word: "wiry", clue: "Thin and strong" },
  { word: "rock", clue: "Solid mineral" },
  { word: "deceive", clue: "Mislead or trick" },
  { word: "freezing", clue: "Extremely cold" },
  { word: "panicky", clue: "In a state of panic" },
  { word: "crash", clue: "Violent impact" },
  { word: "suffer", clue: "Experience pain or distress" },
  { word: "amazing", clue: "Incredible" },
  { word: "sweltering", clue: "Excessively hot" },
  { word: "gigantic", clue: "Enormous in size" },
  { word: "sail", clue: "Propel a boat through water" },
  { word: "stroke", clue: "Gentle movement" },
  { word: "stuff", clue: "Material things" },
  { word: "scientific", clue: "Based on systematic study" },
  { word: "last", clue: "Final" },
  { word: "development", clue: "Process of growth and progress" },
  { word: "straw", clue: "Tube for drinking" },
  { word: "thunder", clue: "Loud noise during a storm" },
  { word: "terrific", clue: "Exceptionally good" },
  { word: "dependent", clue: "Relying on something or someone" },
  { word: "play", clue: "Engage in a fun activity" },
  { word: "sleepy", clue: "Feeling drowsy" },
  { word: "superb", clue: "Excellent" },
  { word: "dogs", clue: "Canine companions" },
  { word: "hair", clue: "Filament covering the head" },
  { word: "unsuitable", clue: "Not appropriate" },
  { word: "river", clue: "Body of flowing water" },
  { word: "pocket", clue: "Small cloth pouch" },
  { word: "bite-sized", clue: "Small enough to be eaten in one bite" },
  { word: "chin", clue: "Protruding part of the face" },
  { word: "snow", clue: "Cold, white precipitation" },
  { word: "jolly", clue: "Merry and cheerful" },
  { word: "behave", clue: "Act in a particular way" },
  { word: "rob", clue: "Steal from" },
  { word: "discreet", clue: "Careful and cautious" },
  { word: "trick", clue: "Deceptive action" },
  { word: "snore", clue: "Make a loud breathing sound while sleeping" },
  { word: "perfect", clue: "Flawless" },
  { word: "war", clue: "Conflict between nations" },
  { word: "pink", clue: "Color of flowers" },
  { word: "pickle", clue: "Vegetable preserved in vinegar" },
  { word: "magic", clue: "Supernatural power" },
  { word: "trashy", clue: "Lacking value or quality" },
  { word: "answer", clue: "Response to a question" },
  { word: "lake", clue: "Large body of water" },
  { word: "loutish", clue: "Rude and disrespectful" },
  { word: "real", clue: "Genuine" },
  { word: "shop", clue: "Retail store" },
  { word: "alive", clue: "Living" },
  { word: "bawdy", clue: "Indecent or obscene" },
  { word: "likeable", clue: "Easy to like" },
  { word: "heavenly", clue: "Divine or celestial" },
  { word: "rotten", clue: "Decayed or spoiled" },
  { word: "scarecrow", clue: "Figure used to frighten birds" },
  { word: "rabid", clue: "Furious or fanatical" },
  { word: "scorch", clue: "Burn slightly" },
  { word: "eggnog", clue: "Creamy holiday beverage" },
  { word: "third", clue: "Ordinal number after second" },
  { word: "scratch", clue: "Mark made by scraping" },
  { word: "grotesque", clue: "Bizarre or disturbing" },
  { word: "undesirable", clue: "Not wanted or wished for" },
  { word: "inconclusive", clue: "Not leading to a clear result" },
  { word: "gusty", clue: "Characterized by strong winds" },
  { word: "grade", clue: "Letter or number indicating quality" },
  { word: "hope", clue: "Optimistic feeling" },
  { word: "motionless", clue: "Without movement" },
  { word: "receive", clue: "Be given or presented with" },
  { word: "hall", clue: "Corridor or large room in a building" },
  { word: "heady", clue: "Intoxicating or exhilarating" },
  { word: "order", clue: "Arrangement or organization" },
  { word: "synonymous", clue: "Having the same meaning" },
  { word: "sweet", clue: "Sugary and pleasant" },
  { word: "fearless", clue: "Without fear" },
  { word: "attraction", clue: "Appealing quality" },
  { word: "grain", clue: "Small hard seed" },
  { word: "introduce", clue: "Make known for the first time" },
  { word: "erect", clue: "Upright" },
  { word: "unruly", clue: "Difficult to control" },
  { word: "found", clue: "Discover or establish" },
  { word: "cart", clue: "Transportation device with wheels" },
  { word: "tart", clue: "Sour or acidic" },
  { word: "ill", clue: "Sick" },
  { word: "kitty", clue: "Small domesticated feline" },
  { word: "sound", clue: "Audible vibration" },
  { word: "work", clue: "Activity involving mental or physical effort" },
  { word: "ill-fated", clue: "Unlucky" },
  { word: "toothsome", clue: "Delicious" },
  { word: "outstanding", clue: "Exceptional or excellent" },
  { word: "weather", clue: "Atmospheric conditions" },
  { word: "giraffe", clue: "Tall African mammal" },
  { word: "furniture", clue: "Household items such as chairs and tables" },
  { word: "reflect", clue: "Throw back light or sound" },
  { word: "veil", clue: "Thin fabric worn to conceal" },
  { word: "wiggly", clue: "Moving in a twisting or squirming motion" },
  { word: "far-flung", clue: "Distant or remote" },
  { word: "downtown", clue: "Central part of a city" },
  { word: "crawl", clue: "Move slowly on hands and knees" },
  { word: "knot", clue: "Tangled or twisted" },
  { word: "analyze", clue: "Examine in detail" },
  { word: "precious", clue: "Valuable and cherished" },
  { word: "land", clue: "Earth's surface" },
  { word: "rail", clue: "Bar for support or transportation" },
  { word: "tacit", clue: "Implied without being stated" },
  { word: "mighty", clue: "Powerful" },
  { word: "careful", clue: "Taking precautions" },
  { word: "notebook", clue: "Paperbound pad" },
  { word: "comparison", clue: "Evaluating similarities and differences" },
  { word: "nerve", clue: "Bundle of fibers transmitting impulses" },
  { word: "cynical", clue: "Distrustful or pessimistic" },
  { word: "ducks", clue: "Waterfowl" },
  { word: "milky", clue: "Resembling or containing milk" },
  { word: "brush", clue: "Tool with bristles" },
  { word: "petite", clue: "Small and trim" },
  { word: "coil", clue: "Spiral or twisted shape" },
  { word: "abashed", clue: "Embarrassed" },
  { word: "dock", clue: "Area for loading and unloading boats" },
  { word: "teeth", clue: "Hard white structures in the mouth" },
  { word: "poised", clue: "Balanced or self-assured" },
  { word: "sweater", clue: "Knitted garment for the upper body" },
  { word: "loving", clue: "Showing affection" },
  { word: "murky", clue: "Dark or gloomy" },
  { word: "leg", clue: "Part of the body used for standing and walking" },
  { word: "ruthless", clue: "Merciless" },
  { word: "number", clue: "Numeric value" },
  { word: "sugar", clue: "Sweet substance" },
  { word: "rainstorm", clue: "Heavy rainfall with thunder and wind" },
  { word: "fortunate", clue: "Lucky" },
  { word: "wealthy", clue: "Rich" },
  { word: "bloody", clue: "Covered or stained with blood" },
  { word: "eye", clue: "Organ of sight" },
  { word: "stew", clue: "Slowly cooked dish of meat and vegetables" },
  { word: "learn", clue: "Acquire knowledge" },
  { word: "clever", clue: "Intelligent and resourceful" },
  { word: "cute", clue: "Endearing or adorable" },
  { word: "many", clue: "A large number" },
  { word: "low", clue: "Not high" },
  { word: "expensive", clue: "Costly" },
  { word: "protective", clue: "Intended to keep safe" },
  { word: "guitar", clue: "Musical instrument with strings" },
  { word: "stage", clue: "Platform for performers" },
  { word: "married", clue: "In a legally recognized union" },
  { word: "three", clue: "Number after two" },
  { word: "cloistered", clue: "Sheltered and secluded" },
  { word: "idea", clue: "Concept or thought" },
  { word: "impartial", clue: "Unbiased" },
  { word: "charming", clue: "Attractive and pleasing" },
  { word: "teaching", clue: "Imparting knowledge" },
  { word: "eight", clue: "Number after seven" },
  { word: "buzz", clue: "Sound made by bees" },
  { word: "cake", clue: "Sweet baked dessert" },
  { word: "tiresome", clue: "Boring or exhausting" },
  { word: "business", clue: "Commercial activity" },
  { word: "white", clue: "Color of snow" },
  { word: "winter", clue: "Coldest season" },
  { word: "symptomatic", clue: "Showing symptoms" },
  { word: "note", clue: "Written message" },
  { word: "hug", clue: "Embrace" },
  { word: "crazy", clue: "Mentally deranged" },
  { word: "elderly", clue: "Old" },
  { word: "abrupt", clue: "Sudden and unexpected" },
  { word: "steer", clue: "Guide or control" },
  { word: "scribble", clue: "Write quickly and untidily" },
  { word: "historical", clue: "Related to the past" },
  { word: "few", clue: "Not many" },
  { word: "matter", clue: "Substance or material" },
  { word: "premium", clue: "High quality" },
  { word: "curved", clue: "Bent or rounded" },
  { word: "standing", clue: "Erect or upright" },
  { word: "ashamed", clue: "Feeling shame or guilt" },
  { word: "object", clue: "Physical thing" },
  { word: "giant", clue: "Extremely large" },
  { word: "picayune", clue: "Trivial or of little value" },
  { word: "parallel", clue: "Extending in the same direction" },
  { word: "tangy", clue: "Having a sharp taste" },
  { word: "decision", clue: "Conclusion or resolution" },
  { word: "fluttering", clue: "Moving with light and rapid motion" },
  { word: "shave", clue: "Trim or cut facial hair" },
  { word: "pumped", clue: "Energized or excited" },
  { word: "smooth", clue: "Even and without roughness" },
  { word: "wistful", clue: "Full of longing or yearning" },
  { word: "embarrassed", clue: "Feeling self-conscious or ashamed" },
  { word: "tested", clue: "Subjected to examination" },
  { word: "coast", clue: "Land next to the sea" },
  { word: "impossible", clue: "Not able to be done" },
  { word: "future", clue: "Time yet to come" },
  { word: "female", clue: "Of the feminine sex" },
  { word: "pest", clue: "Annoying or harmful organism" },
  { word: "voracious", clue: "Very hungry or eager" },
  { word: "stay", clue: "Remain in a particular place" },
  { word: "multiply", clue: "Reproduce or increase" },
  { word: "lean", clue: "Tilt or incline" },
  { word: "placid", clue: "Calm and peaceful" },
  { word: "agreement", clue: "Harmony or concord" },
  { word: "grab", clue: "Take hold of suddenly" },
  { word: "name", clue: "Word or phrase used to identify something" },
  { word: "ambiguous", clue: "Open to interpretation" },
  { word: "bitter", clue: "Having a harsh taste" },
  { word: "fanatical", clue: "Excessively enthusiastic" },
  { word: "husky", clue: "Strong and deep" },
  { word: "tent", clue: "Portable shelter" },
  { word: "puzzling", clue: "Mysterious or confusing" },
  { word: "lying", clue: "Not telling the truth" },
  { word: "hurry", clue: "Move quickly" },
  { word: "shrill", clue: "High-pitched and piercing" },
  { word: "roomy", clue: "Spacious" },
  { word: "shocking", clue: "Causing surprise or dismay" },
  { word: "class", clue: "Educational group" },
  { word: "try", clue: "Attempt" },
  { word: "mere", clue: "Simple or basic" },
  { word: "injure", clue: "Harm or wound" },
  { word: "offend", clue: "Cause displeasure or resentment" },
  { word: "well-off", clue: "Financially comfortable" },
  { word: "lunch", clue: "Midday meal" },
  { word: "inquisitive", clue: "Eager for knowledge" },
  { word: "cold", clue: "Low temperature" },
  { word: "tedious", clue: "Boring and tiresome" },
  { word: "fat", clue: "Adipose tissue" },
  { word: "question", clue: "Interrogative expression" },
  { word: "quirky", clue: "Unconventional or eccentric" },
  { word: "wrist", clue: "Joint between hand and arm" },
  { word: "whirl", clue: "Spin rapidly" },
  { word: "shoe", clue: "Footwear" },
  { word: "ice", clue: "Solid form of water" },
  { word: "boorish", clue: "Rude and unrefined" },
  { word: "staking", clue: "Marking with a stake" },
  { word: "spot", clue: "Small mark or stain" },
  { word: "instinctive", clue: "Natural or intuitive" },
  { word: "prose", clue: "Ordinary language" },
  { word: "lettuce", clue: "Leafy green vegetable" },
  { word: "unaccountable", clue: "Unable to be explained" },
  { word: "whine", clue: "Complain in a high-pitched voice" },
  { word: "clam", clue: "Shellfish" },
  { word: "nosy", clue: "Curious in an intrusive way" },
  { word: "half", clue: "One of two equal parts" },
  { word: "yielding", clue: "Readily giving in to others" },
  { word: "wide", clue: "Having a large distance from side to side" },
  { word: "psychedelic", clue: "Vivid and intense in color" },
  { word: "fast", clue: "Quick or speedy" },
  { word: "thread", clue: "Thin strand of a fiber" },
  { word: "mom", clue: "Mother" },
  { word: "bulb", clue: "Plant part for growing underground" },
  { word: "hesitant", clue: "Uncertain or cautious" },
  { word: "boy", clue: "Young male" },
  { word: "ban", clue: "Prohibit" },
  { word: "vein", clue: "Blood vessel" },
  { word: "crabby", clue: "Grumpy or irritable" },
  { word: "interfere", clue: "Meddle or get involved" },
  { word: "obscene", clue: "Offensive or indecent" },
  { word: "flagrant", clue: "Glaringly obvious" },
];

export default wordClues;
